# Generated by Django 4.2.7 on 2023-11-10 10:58

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_buy', models.IntegerField(verbose_name='Einkauf')),
                ('energy_sell', models.IntegerField(verbose_name='Einspeisung')),
                ('comment', models.TextField()),
                ('date_read', models.DateField(auto_now_add=True, verbose_name='Ablesedatum')),
            ],
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
    ]
