# Generated by Django 4.2.7 on 2024-02-13 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydata',
            name='last_change',
            field=models.DateField(auto_now=True, verbose_name='Letze Änderung'),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='date_read',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Ablesedatum'),
        ),
    ]
